# Generated by Django 4.0.5 on 2022-07-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
